Exp_name: image256

Modality: 'video'

Training:
    Batch_size: 50
    Max_epoch: 10
    learning_rate: 1e-3
    seed: 25
    classes_num: 4

Model:
    name: MobileViT_XXS

Workspace: 'video_workspace'