Exp_name: vit-image-2(1e-3)sigle1

Modality: 'video'

Training:
    Batch_size: 50
    Max_epoch: 300
    learning_rate: 1e-3
    seed: 25
    classes_num: 4

Model:
    name: ViT3D

Workspace: 'video_workspace'