Exp_name: Vit_Panns(1e-5)nofreeze

Modality: 'audio'

Training:
    Batch_size: 200
    Max_epoch: 300
    learning_rate: 1e-5
    seed: 25
    classes_num: 4
Audio_features:
    sample_rate: 64000
    window_size: 2048
    hop_size: 1024
    mel_bins: 128
    fmin: 1
    fmax: 128000

Model: ViT
Model_pretrained: Cnn6

Workspace: 'Audio_workplaces'