Exp_name: BC_Resnet-64k

Modality: 'audio'

Training:
    Batch_size: 200
    Max_epoch: 400
    learning_rate: 1e-3
    seed: 20
    classes_num: 4
Audio_features:
    sample_rate: 64000
    window_size: 2048
    hop_size: 1024
    mel_bins: 64
    fmin: 1
    fmax: 128000

Model: BC_ResNet

Workspace: 'Fish_workspace'

