Exp_name: efficientnet_b7
Modality: 'audio'

Training:
    Batch_size: 10
    Max_epoch: 400
    learning_rate: 1e-3
    seed: 25
    classes_num: 4

Audio_features:
    sample_rate: 64000
    window_size: 2048
    hop_size: 1024
    mel_bins: 64
    fmin: 1
    fmax: 128000

Model: efficientnet_b7

Workspace: 'Fish_workspace'
